// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package es.s2o.automated.test.core.model;

import com.typesafe.config.Config;

import es.s2o.automated.test.core.conf.AbsisConstants;

public class UsuariBuilder extends UsuariBuilderBase<UsuariBuilder> {

	public static UsuariBuilder usuari() {
		return new UsuariBuilder();
	}

	public UsuariBuilder() {
		super(new Usuari());
	}

	public Usuari build() {
		return getInstance();
	}

	public static Usuari configUserBuilder(Config config) {
		return new UsuariBuilder().withModoDemo(config.getBoolean(AbsisConstants.MODO_DEMO))
				.withUsername(config.getString(AbsisConstants.USERNAME))
				.withUsernameDC(config.getString(AbsisConstants.USERNAME_DC))
				.withPasswordIMS(config.getString(AbsisConstants.PASSWORD_IMS))
				.withPasswordAGS(config.getString(AbsisConstants.PASSWORD_AGS))
				.withOficinaContable(config.getString(AbsisConstants.OFICINA_CONTABLE))
				.withIms(config.getString(AbsisConstants.IMS)).build();
	}
}

class UsuariBuilderBase<GeneratorT extends UsuariBuilderBase<GeneratorT>> {
	private final Usuari instance;

	protected UsuariBuilderBase(Usuari aInstance) {
		instance = aInstance;
	}

	protected Usuari getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withModoDemo(boolean aValue) {
		instance.setModoDemo(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUsername(String aValue) {
		instance.setUsername(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUsernameDC(String aValue) {
		instance.setUsernameDC(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPasswordIMS(String aValue) {
		instance.setPasswordIMS(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPasswordAGS(String aValue) {
		instance.setPasswordAGS(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withOficinaContable(String aValue) {
		instance.setOficinaContable(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIms(String aValue) {
		instance.setIms(aValue);

		return (GeneratorT) this;
	}
}
